## 1. Basic Python Commands

In [3]:
x = [1,2,3]
y = [4,5,6]
x + y

[1, 2, 3, 4, 5, 6]

## 2. Introduction to Numpy

In [4]:
import numpy as np

### `x + y`

In [5]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x + y 

array([5, 7, 9])

###  `x.ndim`, `x.dtype`, `x.shape`

In [16]:
# two-dimensional array
x = np.array([[1,3],
              [3,5]])
x

array([[1, 3],
       [3, 5]])

In [17]:
x.ndim  # number of dimensions

2

In [18]:
x.dtype

dtype('int64')

In [14]:
x.shape

(2, 2)

In [15]:
type(x.shape)

tuple

### `x.sum()`, `np.sum(x)`

In [19]:
x = np.array([1,2,3,4])
x.sum()

10

In [20]:
np.sum(x)

10

### `x.reshape()`, `x.T`

In [27]:
x = np.array([1,2,3,4,5,6])
x = x.reshape((2,3))  #reshape a array
x

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
x[0,1]

2

In [29]:
x[0,0] = 999
x

array([[999,   2,   3],
       [  4,   5,   6]])

In [30]:
x.T

array([[999,   4],
       [  2,   5],
       [  3,   6]])

In [31]:
x.shape, x.ndim, x.T  #output is a tuple

((2, 3),
 2,
 array([[999,   4],
        [  2,   5],
        [  3,   6]]))

### `np.sqrt(x)`, `x**2`, `x**0.5`

In [32]:
x = np.array([2,3,4,5])

np.sqrt(x)

array([1.41421356, 1.73205081, 2.        , 2.23606798])

In [33]:
x**2

array([ 4,  9, 16, 25])

In [34]:
x**0.5

array([1.41421356, 1.73205081, 2.        , 2.23606798])

### `np.random.normal()`, `np.corrcoef(x, y)`

In [38]:
# N(0, 1) random numbers
x = np.random.normal(size = 50)
x

array([ 0.4321877 , -0.27001208, -0.85613143,  0.4551613 ,  0.61991003,
       -0.7643731 , -1.02380919, -0.4920776 ,  0.11112302,  0.30005456,
        1.11128581, -1.33334327, -0.66156227,  1.18308531, -0.43090325,
        0.94652481, -1.15668134, -0.02009608,  0.62400314,  0.72984108,
        0.49135139,  1.04564784, -0.8717486 , -0.36491059,  0.70453782,
        0.18558736,  0.23741577, -0.83564294,  0.53924255, -0.2151277 ,
       -1.66037949, -0.65802441,  1.93913109,  0.35407047, -1.00971682,
        1.03825428,  1.29692993, -0.1312429 ,  1.51808158,  0.4432469 ,
       -1.54687153, -0.51150382, -2.01243602, -1.13807306,  0.66134797,
        0.14313148, -1.08496805, -0.34832064, -0.81648005, -0.38383444])

In [39]:
y = x + np.random.normal(loc=50, scale=1, size=50)
y

array([51.45258101, 48.13574507, 48.82732741, 49.5895827 , 50.51625701,
       46.38618593, 48.15153298, 49.51625709, 51.60033161, 51.17359901,
       50.45388286, 48.73597279, 49.84547489, 51.1137972 , 50.70664341,
       50.04796941, 47.96688317, 49.85871722, 51.40917583, 50.74116698,
       49.22337057, 50.13139642, 49.80121056, 49.70306163, 49.24719857,
       50.50776628, 51.4325157 , 47.77291709, 51.6484495 , 48.71830928,
       50.347161  , 49.95869465, 50.95289906, 50.50533124, 49.56742806,
       52.21392473, 52.05452079, 50.77098835, 51.65517261, 50.22363326,
       49.19823956, 49.69896209, 48.05308574, 47.84247762, 49.66739516,
       48.91935185, 48.20228857, 48.85088078, 49.72848073, 50.26181087])

In [41]:
np.corrcoef(x,y)

array([[1.        , 0.65426309],
       [0.65426309, 1.        ]])

### random seeds: `np.random.default_rng(seed)`

The object `rng` has essentially all the random number generating methods found in `np.random`. Hence, to generate normal data we use `rng.normal()`.

In [42]:
rng = np.random.default_rng(1303)
rng.normal(size = 5)

array([ 0.81896526, -0.21497121, -2.03072919,  0.22681229, -0.82806113])

In [44]:
rng2 = np.random.default_rng(1303)
rng2.normal(size=5)

array([ 0.81896526, -0.21497121, -2.03072919,  0.22681229, -0.82806113])

In [48]:
np.random.default_rng(1303).normal(size=5)

array([ 0.81896526, -0.21497121, -2.03072919,  0.22681229, -0.82806113])

### `np.var(y)`, `np.mean(y)`, `np.std(y)`

In [49]:
rng = np.random.default_rng(3)

y = rng.standard_normal(10)

np.mean(y), y.mean()

(-0.1126795190952861, -0.1126795190952861)